<div class="container">
	<h1 class="text-center">Perfis</h1>
	<br />
	<br />
	<p>
		<a class="btn btn-primary"
			href="<?php echo $this->basePath(); ?>/role/form" rel="tooltip" data-container="body" data-placement="bottom" title="Criar um perfil" ><span class="glyphicon glyphicon-plus"></span> Novo</a>
	</p>
	<table class="table table-bordered">
	<thead>
		<tr>
			<th>Nome</th>
			<th style="width: 5%;">Admin?</th>
			<th style="width: 15%;">Ação</th>
		</tr>
	</thead>
	<tbody>
		<?php if($this->roles) { ?>
		    <?php foreach($this->roles as $role){ 
		    	if($role->rolId != 102) {?>
		   		<tr id="roleRow<?php echo $role->rolId ?>">
					<td><?php echo $role->name; ?></td>
					<td><?php $role->isAdmin?print 'Sim':print 'Não'; ?></td>
					<td><a class='glyphicon glyphicon-edit' <?php print "href='".$this->basePath()."/role/form?id=".$role->rolId."'"?> rel="tooltip" data-container="body" data-placement="bottom" title="Modificar informações do perfil" ></a> 
					<a class='glyphicon glyphicon-trash' href='javascript:getRole("<?php echo $role->rolId ?>","<?php echo $role->name ?>");' rel="tooltip" data-container="body" data-placement="bottom" title="Remover perfil" ></a></td>
				</tr>
	    <?php  }
	    	}
	   	}?>
   	</tbody>
</table>
</div>
<br />
<div class="modal fade" id="remove" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">×</button>
				<h4 class="modal-title" id="myModalLabel">Remover perfil</h4>
			</div>
			<div class="modal-body">
				<form id="rename" method="post">
					<span id="roleNameLabel"></span>
					<input type="hidden" id='hiddenId' value="" />
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
				<a class="btn btn-primary" href="javascript:removeRole(<?php echo $this->basePath()."'/role/remove'" ?>);">Remover</a>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="removeError" role="dialog"
		aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-hidden="true">×</button>
					<h4 class="modal-title" id="modalTitle">Remover perfil</h4>
				</div>
				<div class="modal-body">
					<form method="post">
						<span id='modalLabelError'></span>
						<input type="hidden" id='hiddenId' value="" />
					</form>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
				</div>
			</div>
		</div>
	</div>
	<script>
var basePath = '<?php echo $this->basePath(); ?>';
</script>