<div class="divUsers">
	<h1 class="text-center">Projetos</h1>
	<br />
	<br />
	<p>
        <a class="btn btn-primary" href="<?php echo $this->basePath(); ?>/project/form" rel="tooltip" data-container="body" data-placement="bottom" title="Criar um projeto"><span class="glyphicon glyphicon-plus"></span> Novo</a>
        <a class="btn btn-primary" href="<?php echo $this->basePath(); ?>/user/associateProjects" rel="tooltip" data-container="body" data-placement="bottom" title="Definir/alterar os projetos associados aos usuários">Associar usuários a projetos</a>
	</p>
	<div class="table-responsive">
		<table class="table table-bordered tablesorter prj-sort">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Descrição</th>
					<th>Link</th>
					<th>Ação</th>
				</tr>
			</thead>
		    <tbody>
		    <?php 
		    if($this->projects) { 
		    	foreach($this->projects as $project):
		    ?>
				    <tr>
						<td id="prjName<?php echo $project->prjId ?>" class="<?php !$project->active?print 'link-disable':'' ?>"><?php echo $project->projectName; ?></td>
						<td id="prjDesc<?php echo $project->prjId ?>" class="<?php !$project->active?print 'link-disable':'' ?>"><?php echo $project->description; ?></td>
						<td id="prjLink<?php echo $project->prjId ?>" class="<?php !$project->active?print 'link-disable':'' ?>"><?php echo $project->link; ?></td>
						<td>
							<a id="editPrjBtn<?php echo $project->prjId ?>" class="glyphicon glyphicon-edit <?php !$project->active?print 'link-disable':'' ?>" href='<?php echo $this->basePath()."/project/form?id=".$project->prjId; ?>' rel="tooltip" data-container="body" data-placement="bottom" title="Modificar informações do projeto"></a>
							<a id="enableDisablePrjBtn<?php echo $project->prjId ?>" class="glyphicon <?php $project->active?print ' glyphicon-ban-circle ':print ' glyphicon-ok-circle' ?>" <?php $project->active?print "href='javascript:disableProject(".$project->prjId.", \"".$this->basePath()."/project/disable\");'":print "href='javascript:enableProject(".$project->prjId.", \"".$this->basePath()."/project/enable\");'" ?> rel="tooltip" data-container="body" data-placement="bottom" title="<?php $project->active?print 'Desativar projeto':print 'Ativar projeto' ?>"></a>
						</td>
					</tr>
		    <?php 
		    	endforeach; 
		    }
		    ?>
		    </tbody>
		</table>
	</div>
</div>
<script>
var basePath = '<?php echo $this->basePath(); ?>';
</script>