<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Project\Module'                        => __DIR__ . '/Module.php',
    'Project\Controller\ProjectController' => __DIR__ . '/src/Project/Controller/ProjectController.php',
    'ProjectTest\Framework\TestCase'        => __DIR__ . '/tests/Project/Framework/TestCase.php',
    'ProjectTest\SampleTest'                => __DIR__ . '/tests/Project/SampleTest.php',
);
