<script src="<?php echo $this->basePath(); ?>/js/jquery.mask.min.js"
	type="text/javascript"></script>
<div class="container">
	<h2 class="text-center">Workspace</h2>
	<br />
	<div class="acesso">
		<div class="row clearfix">
			<div class="col-md-6 column">
				<div class="pull-left">
					<br /> <span class="lead">Projetos</span> <select
						id="combo_box_prj" rel="tooltip" data-container="body"
						data-placement="right" title="Seleção de projetos"
						class="form-control input-md" onchange="selectNewPrj(this)">
						<option selected="selected" value="">Projetos</option>
						<?php
						if (! empty ( $this->prjs )) {
							if ($this->prjs) {
								foreach ( $this->prjs as $count => $prj ) :
									echo "<option value='" . $prj->prjId . "' " . (($this->current_prj && $this->current_prj->prjId == $prj->prjId) ? ("selected") : ("")) . ">" . (++ $count) . '. ' . $prj->projectName . ((! $prj->active) ? (" (Desativado)") : ("")) . "</option>";
								endforeach
								;
							}
						} else
							echo "<option value=''>Não existem projetos.</option>";
						?>
					</select>
				</div>
			</div>
			<div class="col-md-12 column">
				<br /> <span class="lead">Mapa</span>
				<div class="bordaPrj">
					<div id="map" class="map" style="height: 380px;">
						<div id="toolbar">
							<div id="pan" title="Arrastar mapa" class="btn btn-default active">
								<i class="mdi mdi-arrow-all"></i>
							</div>
							<div id="drawPoint" title="Desenhar ponto" class="btn btn-default">
								<i class="mdi mdi-map-marker"></i>
							</div>
							<div id="drawLine" title="Desenhar linha" class="btn btn-default">
								<i class="mdi mdi-vector-polyline"></i>
							</div>
							<div id="drawPolygon" title="Desenhar polígono" class="btn btn-default">
								<i class="mdi mdi-vector-polygon"></i>
							</div>
							<div id="edit" title="Editar" class="btn btn-default">
								<i class="mdi mdi-tooltip-edit"></i>
							</div>
							<div id="erase" title="Excluir" class="btn btn-danger">
								<i class="mdi mdi-delete"></i>
							</div>
							<div id="commit" title="Commit" class="btn btn-success">
								<i class="mdi mdi-checkbox-marked-circle"></i>
							</div>
							<div id="push" title="Realizar push para servidor" class="btn btn-primary">
								<i class="mdi mdi-cloud-upload"></i>
							</div>
						</div>
					</div>

				</div>
			</div>
			<div class="col-md-12 column">
				<br /> <span class="lead">Histórico de commits</span>
				<div class="bordaPrj table-responsive table-overflow">
					<table id="shapeTable" class="table table-striped table-bordered">
					<?php if(empty($this->shapes)){?>
						<thead id="noshapeThead">
							<tr>
								<th>Nenhum commit realizado</th>
							</tr>
						</thead>
						<thead hidden="hidden" id="shapeThead">
							<tr>
								<th>Arquivo</th>
								<th>Data de envio</th>
							</tr>
						</thead>
						<tbody>
					<?php }else {?>
						<thead id="shapeThead">
							<tr>
								<th>Arquivo</th>
								<th>Data de envio</th>
							</tr>
						</thead>
						<tbody>
							<?php
						foreach ( $this->shapes as $shape ) {
							$date = $shape->uploadDate;
							?>
							<tr>
								<td><?php echo $shape->fileName ?></td>
								<td><?php echo $date->format('d-m-Y H:i:s') ?></td>
							</tr>
							<?php
						}
						?>
						</tbody>
					<?php }?>
				</table>
				</div>
			</div>
		</div>
	</div>
	<?php
	$flash = $this->flashMessenger ();
	$flash->setMessageOpenFormat ( '<div%s>
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
		    &times;
		</button>
		<div>' )->setMessageCloseString ( '</div></div>' );
	
	echo $flash->render ( 'workspace-error', array (
			'alert',
			'alert-dismissable',
			'alert-danger',
			'alert-messages',
			'flash-messages' 
	) );
	echo $flash->render ( 'workspace-info', array (
			'alert',
			'alert-dismissable',
			'alert-info',
			'alert-messages',
			'flash-messages' 
	) );
	echo $flash->render ( 'workspace-warning', array (
			'alert',
			'alert-dismissable',
			'alert-warning',
			'alert-messages',
			'flash-messages' 
	) );
	echo $flash->render ( 'workspace-success', array (
			'alert',
			'alert-dismissable',
			'alert-success',
			'alert-messages',
			'flash-messages' 
	) );
	?>

	<div id="ajax_workspace_error"
		onclick="$('#ajax_workspace_error').hide()"
		class="alert alert-dismissable alert-danger alert-messages"
		hidden="hidden">
		<button class="close" type="button">×</button>
		<div id="ajax_workspace_error_msg"></div>
	</div>
	<div id="ajax_workspace_success"
		class="alert alert-dismissable alert-success alert-messages"
		hidden="hidden">
		<button class="close" onclick="$('#ajax_workspace_success').hide()"
			type="button">×</button>
		<div id="ajax_workspace_success_msg"></div>
	</div>
	<div id="ajax_workspace_warning"
		class="alert alert-dismissable alert-warning alert-messages"
		hidden="hidden">
		<button class="close" onclick="$('#ajax_workspace_warning').hide()"
			type="button">×</button>
		<div id="ajax_workspace_warning_msg"></div>
	</div>

	<div class="container">
		<div class="row clearfix">
			<div class="col-md-12 column">
				<!-- Renomear -->
				<div class="modal fade" id="modal-rename" role="dialog"
					aria-labelledby="modal" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<!-- <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> -->
								<h4 class="modal-title" id="modal-rename-title"></h4>
							</div>
							<div class="modal-body">
								<strong>Novo nome:</strong> <input value="" id="newName"
									type="text" class="form-control" autofocus /> <input
									type="hidden" id='rename-id' value="" /> <span
									id="modal-rename-error" class="errorMessage"></span>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default"
									onclick="closeModal()">Fechar</button>
								<a id="modal-rename-btn" href="" class="btn btn-primary">Renomear</a>
							</div>
						</div>
					</div>
				</div>
				<!-- Remover -->
				<div class="modal fade" id="modal-remove" role="dialog"
					aria-labelledby="modal" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<!-- <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> -->
								<h4 class="modal-title" id="modal-remove-title"></h4>
							</div>
							<div class="modal-body">
								<span id="modal-remove-message"></span> <input type="hidden"
									id='remove-id' value="" />
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default"
									data-dismiss="modal">Fechar</button>
								<a id="modal-remove-btn" href="" class="btn btn-primary">Remover</a>
							</div>
						</div>
					</div>
				</div>
				<!-- Passos validação shape -->
				<div class="modal fade" id="modal-info" role="dialog"
					aria-labelledby="modal" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal"
									aria-hidden="true">×</button>
								<h4 class="modal-title">Regras da validação de shapefiles</h4>
							</div>
							<div class="modal-body">
								<label>A validação de shapefiles segue os passos abaixo:</label>
								<div id="rules"></div>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default"
									data-dismiss="modal">Fechar</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
var basePath = '<?php echo $this->basePath(); ?>';
var fileSizeInBytes = '<?php echo $this->fileSizeInBytes; ?>';
var fileSizeString = '<?php echo $this->fileSizeString; ?>';
var projectName = '<?php echo $this->current_prj->projectName; ?>';
var tableName = '<?php echo $this->tableName; ?>';
</script>