<script src="<?php echo $this->basePath(); ?>/js/jquery.mask.min.js"
	type="text/javascript"></script>
<div class="container">
	<h2 class="text-center">Workspace</h2>
	<br />
	<div class="acesso">
		<div class="row clearfix">
			<div class="col-md-6 column">
				<div class="pull-left">
					<br /> <span class="lead">Projetos</span> <select
						id="combo_box_prj" rel="tooltip" data-container="body"
						data-placement="right" title="Seleção de projetos"
						class="form-control input-md" onchange="selectNewPrj(this)">
						<option selected="selected" value="">Projetos</option>
						<?php
						if (! empty ( $this->prjs )) {
							if ($this->prjs) {
								foreach ( $this->prjs as $count => $prj ) :
									echo "<option value='" . $prj->prjId . "' " . (($this->current_prj && $this->current_prj->prjId == $prj->prjId) ? ("selected") : ("")) . ">" . (++ $count) . '. ' . $prj->projectName . ((! $prj->active) ? (" (Desativado)") : ("")) . "</option>";
								endforeach
								;
							}
						} else
							echo "<option value=''>Não existem projetos.</option>";
						?>
					</select>
				</div>
			</div>
			<div class="col-md-12 column">
				<br /> <span class="lead">Mapa</span>
				<div class="bordaPrj">
					<div id="map" class="map" style="height: 380px;">
						<div id="toolbar">
							<div id="pan" title="Arrastar mapa"
								class="btn btn-default active">
								<i class="mdi mdi-arrow-all"></i>
							</div>
							<div id="drawPoint" title="Desenhar ponto"
								class="btn btn-default">
								<i class="mdi mdi-map-marker"></i>
							</div>
							<div id="drawLine" title="Desenhar linha" class="btn btn-default">
								<i class="mdi mdi-vector-polyline"></i>
							</div>
							<div id="drawPolygon" title="Desenhar polígono"
								class="btn btn-default">
								<i class="mdi mdi-vector-polygon"></i>
							</div>
							<div id="pointDetail" title="Ver detalhes"
								class="btn btn-default">
								<i class="mdi mdi-information"></i>
							</div>
							<div id="edit" title="Editar" class="btn btn-default">
								<i class="mdi mdi-tooltip-edit"></i>
							</div>
							<div id="erase" title="Excluir" class="btn btn-danger">
								<i class="mdi mdi-delete"></i>
							</div>
							<div id="commit" title="Commit" class="btn btn-success"
								data-toggle="modal" data-target="#commit-modal">
								<i class="mdi mdi-checkbox-marked-circle"></i>
							</div>
							<div id="push" title="Realizar push para servidor"
								class="btn btn-primary">
								<i class="mdi mdi-cloud-upload"></i>
							</div>
							<div id="pull" title="Realizar pull do servidor"
								class="btn btn-warning">
								<i class="mdi mdi-cloud-download"></i>
							</div>
						</div>
					</div>

				</div>
			</div>
			<div class="col-md-12 column">
				<br /> <span class="lead">Histórico de commits</span>
				<div class="bordaPrj table-responsive table-overflow">
					<table id="shapeTable" class="table table-striped table-bordered">
					<?php if(empty($this->commits)){?>
						<thead>
							<tr>
								<th>Nenhum commit realizado</th>
							</tr>
						</thead>
						<tbody>
					<?php }else {?>
						<thead>
							<tr>
								<th>Log</th>
							</tr>
						</thead>
						<tbody>
						<?php
						$count = 0;
						foreach ( $this->commits as $commit ) {
							?>
							<tr>
								<?php
								$pos = strpos($commit, 'Commit');
								if($pos !== false){
									echo 
									'<td><strong>' . $commit . '</strong>'.
										'<form  class="pull-right" method="post" action="/workspace/revertCommit" style="display:inline-block">'.
										'<input type="hidden" name="commitId" value="'.substr($commit,9,41). '" />'.
										'<img id="revert-ajax-gif-' . $count . '" class="pull-right" src="/img/ajax-loader.gif" hidden="hidden">'.
										'<input type="submit" value="Revert" onclick="showRevertAjaxGif(' . $count . ')" />'.
										'</form>'.
									'</td>';
								}else{
									echo '<td>' . $commit . '</td>';
								}
								?>
							</tr>
						<?php
						$count++;
						}
						?>
						</tbody>
					<?php }?>
				</table>
				</div>
			</div>
		</div>
	</div>
	<?php
	$flash = $this->flashMessenger ();
	$flash->setMessageOpenFormat ( '<div%s>
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
		    &times;
		</button>
		<div>' )->setMessageCloseString ( '</div></div>' );
	
	echo $flash->render ( 'workspace-error', array (
			'alert',
			'alert-dismissable',
			'alert-danger',
			'alert-messages',
			'flash-messages' 
	) );
	echo $flash->render ( 'workspace-info', array (
			'alert',
			'alert-dismissable',
			'alert-info',
			'alert-messages',
			'flash-messages' 
	) );
	echo $flash->render ( 'workspace-warning', array (
			'alert',
			'alert-dismissable',
			'alert-warning',
			'alert-messages',
			'flash-messages' 
	) );
	echo $flash->render ( 'workspace-success', array (
			'alert',
			'alert-dismissable',
			'alert-success',
			'alert-messages',
			'flash-messages' 
	) );
	?>

	<div class="container">
		<div class="row clearfix">
			<div class="col-md-12 column">
				<!-- Commit Modal -->
				<div id="commit-modal" class="modal fade">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal"
									aria-hidden="true">x</button>
								<h4 class="modal-title">Commitar alterações no repositório local</h4>
							</div>
							<div class="modal-body">
								<form method="post" action="/workspace/commit">
									Mensagem de commit:
									<textarea class="form-control" rows="3" name="commitMsg"></textarea>
									<br>
									<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
									<button id="commit-btn" type="submit" class="pull-right btn btn-success" onclick="showCommitAjaxGif()">Commit</button>
									<img id="commit-ajax-gif" class="pull-right" src="/img/ajax-loader.gif" hidden="hidden">
								</form>
							</div>
						</div>
						<!--modal-content-->
					</div>
					<!--modal-dialog-->
				</div>
				<!--modal-->
				<!-- Insert Point -->
				<div class="modal fade" id="modal-insert-point" role="dialog"
					aria-labelledby="modal" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<!-- <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> -->
								<h4 class="modal-title" id="modal-insert-point-title">Descrição do ponto</h4>
							</div>
							<div class="modal-body">
								<span>Descrição: </span><input type="text"
									id='desc-point' class="form-control input-md" value="" />
							</div>
							<div class="modal-footer">
								<button id='modal-insert-close' type="button" class="btn btn-default"
									data-dismiss="modal">Fechar</button>
								<button id="modal-insert-submit" class="btn btn-primary">Enviar</button>
							</div>
						</div>
					</div>
				</div>
				<div class="modal fade" id="modal-description" role="dialog"
					aria-labelledby="modal" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal"
									aria-hidden="true">×</button>
								<h4 class="modal-title">Descrição do ponto</h4>
							</div>
							<div class="modal-body">
								<label>Descrição:</label>
								<div id="modal-description-point"></div>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default"
									data-dismiss="modal">Fechar</button>
							</div>
						</div>
					</div>
				</div>
				<div class="modal fade" id="modal-push" role="dialog"
					aria-labelledby="modal" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<!-- <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> -->
								<h4 class="modal-title" id="modal-insert-point-title">Realizar <strong>push</strong> para o repositorio remoto</h4>
							</div>
							<form action="workspace/push" method="post">
								<div class="modal-footer">
									<button id='modal-insert-close' type="button" class="btn btn-default"
										data-dismiss="modal">Cancelar</button>
									<button id="modal-push-submit" type="submit" class="btn btn-primary">Push</button>
								</div>
							</form>
						</div>
					</div>
				</div>
				<div class="modal fade" id="modal-pull" role="dialog"
					aria-labelledby="modal" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<!-- <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> -->
								<h4 class="modal-title">Realizar <strong>pull</strong> do repositorio remoto</h4>
							</div>
							<form action="workspace/pull" method="post">
								<div class="modal-footer">
									<button id='modal-insert-close' type="button" class="btn btn-default"
										data-dismiss="modal">Cancelar</button>
									<button id="modal-pull-submit" type="submit" class="btn btn-primary">Pull</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
var basePath = '<?php echo $this->basePath; ?>';
var projectName = '<?php echo $this->current_prj->projectName; ?>';
var tableName = '<?php echo $this->tableName; ?>';
</script>