<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Workspace\Module'                        => __DIR__ . '/Module.php',
    'Workspace\Controller\WorkspaceController' => __DIR__ . '/src/Workspace/Controller/WorkspaceController.php',
    'WorkspaceTest\Framework\TestCase'        => __DIR__ . '/tests/Workspace/Framework/TestCase.php',
    'WorkspaceTest\SampleTest'                => __DIR__ . '/tests/Workspace/SampleTest.php',
);
