<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<div id="sending_loading" style="display: none; text-align: center;">
				<img alt="loading..."
					src="<?php echo $this->basePath();?>/img/ajax-loader.gif">
			</div>
			<form action="<?php echo $this->basePath();?>/reset/resetPassword"
				method="post">
				<div class="row clearfix">
					<div class="col-md-12 column">
						<div class="form-group">
						<?php
						$flash = $this->flashMessenger ();
						$flash->setMessageOpenFormat ( '<div%s>
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
							    &times;
							</button>
							<div>' )->setMessageCloseString ( '</div></div>' );
						
						echo $flash->render ( 'error-email', array (
								'alert',
								'alert-dismissable',
								'alert-danger', 
								'alert-messages', 
								'flash-messages'
						) );
						echo $flash->render ( 'info-email', array (
								'alert',
								'alert-dismissable',
								'alert-info', 
								'alert-messages', 
								'flash-messages'
						) );
						echo $flash->render ( 'default-email', array (
								'alert',
								'alert-dismissable',
								'alert-warning', 
								'alert-messages', 
								'flash-messages'
								
						) );
						echo $flash->render ( 'success-email', array (
								'alert',
								'alert-dismissable',
								'alert-success', 
								'alert-messages', 
								'flash-messages'
						) );
						?>
					</div>
						<div class="page-header">
							<h3>Esquecimento de senha</h3>
							<span class="help-block">Digite abaixo o seu email cadastrado em
								nosso sistema e clique em resetar senha.</span> <span
								class="help-block"> Um link de alteração de senha será enviado
								para seu email, basta acessar o link e definir sua nova senha.
								O prazo para redefinir a senha é de 3 dias, caso ultrapasse o limite, basta definir uma nova senha novamente.</span>
						</div>
						<div class="col-xs-3">
							<p>
								<label for="emailReset">E-mail institucional</label><input id="emailReset" class="form-control" type="text" value="" placeholder="Insira seu e-mail" name="email">
							</p>
						</div>
					</div>
					<div class="col-md-12 column">
						<input class="btn btn-default" type="submit" value="Resetar Senha"
							onclick="showLoadingGif()" title="Resetar sua senha."
							name="reset">
						<button type="button" class="btn btn-default"
							onClick="javascript:window.location.href='<?php echo $this->basePath();?>/'">Cancelar</button>
						<i id="loading"
							class="fa fa-cog fa-spin fa-1x fa-fw margin-bottom"
							style="display: none;"></i>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>